/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseRequestsRouteImport } from './routes/purchase-requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApprovalInboxRouteImport } from './routes/approval-inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfqNewRouteImport } from './routes/rfq.new'
import { Route as RfqRfqIdRouteImport } from './routes/rfq.$rfqId'
import { Route as ReferencesPpmpRouteImport } from './routes/references.ppmp'
import { Route as ReferencesBudgetRouteImport } from './routes/references.budget'
import { Route as ReferencesAppNonCseRouteImport } from './routes/references.app-non-cse'
import { Route as ReferencesAppCseRouteImport } from './routes/references.app-cse'
import { Route as PurchaseRequestsNewRouteImport } from './routes/purchase-requests.new'
import { Route as PurchaseRequestsPrIdRouteImport } from './routes/purchase-requests.$prId'
import { Route as PlanningPpmpRouteImport } from './routes/planning.ppmp'
import { Route as PlanningLibRouteImport } from './routes/planning.lib'
import { Route as PlanningPpmpNewRouteImport } from './routes/planning.ppmp.new'
import { Route as PlanningLibNewRouteImport } from './routes/planning.lib.new'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsRoute = PurchaseRequestsRouteImport.update({
  id: '/purchase-requests',
  path: '/purchase-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalInboxRoute = ApprovalInboxRouteImport.update({
  id: '/approval-inbox',
  path: '/approval-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqNewRoute = RfqNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RfqRoute,
} as any)
const RfqRfqIdRoute = RfqRfqIdRouteImport.update({
  id: '/$rfqId',
  path: '/$rfqId',
  getParentRoute: () => RfqRoute,
} as any)
const ReferencesPpmpRoute = ReferencesPpmpRouteImport.update({
  id: '/references/ppmp',
  path: '/references/ppmp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesBudgetRoute = ReferencesBudgetRouteImport.update({
  id: '/references/budget',
  path: '/references/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesAppNonCseRoute = ReferencesAppNonCseRouteImport.update({
  id: '/references/app-non-cse',
  path: '/references/app-non-cse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesAppCseRoute = ReferencesAppCseRouteImport.update({
  id: '/references/app-cse',
  path: '/references/app-cse',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsNewRoute = PurchaseRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchaseRequestsRoute,
} as any)
const PurchaseRequestsPrIdRoute = PurchaseRequestsPrIdRouteImport.update({
  id: '/$prId',
  path: '/$prId',
  getParentRoute: () => PurchaseRequestsRoute,
} as any)
const PlanningPpmpRoute = PlanningPpmpRouteImport.update({
  id: '/planning/ppmp',
  path: '/planning/ppmp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningLibRoute = PlanningLibRouteImport.update({
  id: '/planning/lib',
  path: '/planning/lib',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningPpmpNewRoute = PlanningPpmpNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlanningPpmpRoute,
} as any)
const PlanningLibNewRoute = PlanningLibNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlanningLibRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/planning/lib': typeof PlanningLibRouteWithChildren
  '/planning/ppmp': typeof PlanningPpmpRouteWithChildren
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/planning/lib/new': typeof PlanningLibNewRoute
  '/planning/ppmp/new': typeof PlanningPpmpNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/planning/lib': typeof PlanningLibRouteWithChildren
  '/planning/ppmp': typeof PlanningPpmpRouteWithChildren
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/planning/lib/new': typeof PlanningLibNewRoute
  '/planning/ppmp/new': typeof PlanningPpmpNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rfq': typeof RfqRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/planning/lib': typeof PlanningLibRouteWithChildren
  '/planning/ppmp': typeof PlanningPpmpRouteWithChildren
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
  '/rfq/$rfqId': typeof RfqRfqIdRoute
  '/rfq/new': typeof RfqNewRoute
  '/planning/lib/new': typeof PlanningLibNewRoute
  '/planning/ppmp/new': typeof PlanningPpmpNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/login'
    | '/purchase-requests'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/users'
    | '/validation'
    | '/planning/lib'
    | '/planning/ppmp'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
    | '/rfq/$rfqId'
    | '/rfq/new'
    | '/planning/lib/new'
    | '/planning/ppmp/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/login'
    | '/purchase-requests'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/users'
    | '/validation'
    | '/planning/lib'
    | '/planning/ppmp'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
    | '/rfq/$rfqId'
    | '/rfq/new'
    | '/planning/lib/new'
    | '/planning/ppmp/new'
  id:
    | '__root__'
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/login'
    | '/purchase-requests'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/users'
    | '/validation'
    | '/planning/lib'
    | '/planning/ppmp'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
    | '/rfq/$rfqId'
    | '/rfq/new'
    | '/planning/lib/new'
    | '/planning/ppmp/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalInboxRoute: typeof ApprovalInboxRoute
  AuditLogsRoute: typeof AuditLogsRoute
  LoginRoute: typeof LoginRoute
  PurchaseRequestsRoute: typeof PurchaseRequestsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RfqRoute: typeof RfqRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ValidationRoute: typeof ValidationRoute
  PlanningLibRoute: typeof PlanningLibRouteWithChildren
  PlanningPpmpRoute: typeof PlanningPpmpRouteWithChildren
  ReferencesAppCseRoute: typeof ReferencesAppCseRoute
  ReferencesAppNonCseRoute: typeof ReferencesAppNonCseRoute
  ReferencesBudgetRoute: typeof ReferencesBudgetRoute
  ReferencesPpmpRoute: typeof ReferencesPpmpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests': {
      id: '/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/purchase-requests'
      preLoaderRoute: typeof PurchaseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-inbox': {
      id: '/approval-inbox'
      path: '/approval-inbox'
      fullPath: '/approval-inbox'
      preLoaderRoute: typeof ApprovalInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/new': {
      id: '/rfq/new'
      path: '/new'
      fullPath: '/rfq/new'
      preLoaderRoute: typeof RfqNewRouteImport
      parentRoute: typeof RfqRoute
    }
    '/rfq/$rfqId': {
      id: '/rfq/$rfqId'
      path: '/$rfqId'
      fullPath: '/rfq/$rfqId'
      preLoaderRoute: typeof RfqRfqIdRouteImport
      parentRoute: typeof RfqRoute
    }
    '/references/ppmp': {
      id: '/references/ppmp'
      path: '/references/ppmp'
      fullPath: '/references/ppmp'
      preLoaderRoute: typeof ReferencesPpmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/budget': {
      id: '/references/budget'
      path: '/references/budget'
      fullPath: '/references/budget'
      preLoaderRoute: typeof ReferencesBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/app-non-cse': {
      id: '/references/app-non-cse'
      path: '/references/app-non-cse'
      fullPath: '/references/app-non-cse'
      preLoaderRoute: typeof ReferencesAppNonCseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/app-cse': {
      id: '/references/app-cse'
      path: '/references/app-cse'
      fullPath: '/references/app-cse'
      preLoaderRoute: typeof ReferencesAppCseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/new': {
      id: '/purchase-requests/new'
      path: '/new'
      fullPath: '/purchase-requests/new'
      preLoaderRoute: typeof PurchaseRequestsNewRouteImport
      parentRoute: typeof PurchaseRequestsRoute
    }
    '/purchase-requests/$prId': {
      id: '/purchase-requests/$prId'
      path: '/$prId'
      fullPath: '/purchase-requests/$prId'
      preLoaderRoute: typeof PurchaseRequestsPrIdRouteImport
      parentRoute: typeof PurchaseRequestsRoute
    }
    '/planning/ppmp': {
      id: '/planning/ppmp'
      path: '/planning/ppmp'
      fullPath: '/planning/ppmp'
      preLoaderRoute: typeof PlanningPpmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/lib': {
      id: '/planning/lib'
      path: '/planning/lib'
      fullPath: '/planning/lib'
      preLoaderRoute: typeof PlanningLibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/ppmp/new': {
      id: '/planning/ppmp/new'
      path: '/new'
      fullPath: '/planning/ppmp/new'
      preLoaderRoute: typeof PlanningPpmpNewRouteImport
      parentRoute: typeof PlanningPpmpRoute
    }
    '/planning/lib/new': {
      id: '/planning/lib/new'
      path: '/new'
      fullPath: '/planning/lib/new'
      preLoaderRoute: typeof PlanningLibNewRouteImport
      parentRoute: typeof PlanningLibRoute
    }
  }
}

interface PurchaseRequestsRouteChildren {
  PurchaseRequestsPrIdRoute: typeof PurchaseRequestsPrIdRoute
  PurchaseRequestsNewRoute: typeof PurchaseRequestsNewRoute
}

const PurchaseRequestsRouteChildren: PurchaseRequestsRouteChildren = {
  PurchaseRequestsPrIdRoute: PurchaseRequestsPrIdRoute,
  PurchaseRequestsNewRoute: PurchaseRequestsNewRoute,
}

const PurchaseRequestsRouteWithChildren =
  PurchaseRequestsRoute._addFileChildren(PurchaseRequestsRouteChildren)

interface RfqRouteChildren {
  RfqRfqIdRoute: typeof RfqRfqIdRoute
  RfqNewRoute: typeof RfqNewRoute
}

const RfqRouteChildren: RfqRouteChildren = {
  RfqRfqIdRoute: RfqRfqIdRoute,
  RfqNewRoute: RfqNewRoute,
}

const RfqRouteWithChildren = RfqRoute._addFileChildren(RfqRouteChildren)

interface PlanningLibRouteChildren {
  PlanningLibNewRoute: typeof PlanningLibNewRoute
}

const PlanningLibRouteChildren: PlanningLibRouteChildren = {
  PlanningLibNewRoute: PlanningLibNewRoute,
}

const PlanningLibRouteWithChildren = PlanningLibRoute._addFileChildren(
  PlanningLibRouteChildren,
)

interface PlanningPpmpRouteChildren {
  PlanningPpmpNewRoute: typeof PlanningPpmpNewRoute
}

const PlanningPpmpRouteChildren: PlanningPpmpRouteChildren = {
  PlanningPpmpNewRoute: PlanningPpmpNewRoute,
}

const PlanningPpmpRouteWithChildren = PlanningPpmpRoute._addFileChildren(
  PlanningPpmpRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalInboxRoute: ApprovalInboxRoute,
  AuditLogsRoute: AuditLogsRoute,
  LoginRoute: LoginRoute,
  PurchaseRequestsRoute: PurchaseRequestsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RfqRoute: RfqRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ValidationRoute: ValidationRoute,
  PlanningLibRoute: PlanningLibRouteWithChildren,
  PlanningPpmpRoute: PlanningPpmpRouteWithChildren,
  ReferencesAppCseRoute: ReferencesAppCseRoute,
  ReferencesAppNonCseRoute: ReferencesAppNonCseRoute,
  ReferencesBudgetRoute: ReferencesBudgetRoute,
  ReferencesPpmpRoute: ReferencesPpmpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
