/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseRequestsRouteImport } from './routes/purchase-requests'
import { Route as PpmpDocumentsRouteImport } from './routes/ppmp-documents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibRouteImport } from './routes/lib'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApprovalInboxRouteImport } from './routes/approval-inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferencesPpmpRouteImport } from './routes/references.ppmp'
import { Route as ReferencesBudgetRouteImport } from './routes/references.budget'
import { Route as ReferencesAppNonCseRouteImport } from './routes/references.app-non-cse'
import { Route as ReferencesAppCseRouteImport } from './routes/references.app-cse'
import { Route as PurchaseRequestsNewRouteImport } from './routes/purchase-requests.new'
import { Route as PurchaseRequestsPrIdRouteImport } from './routes/purchase-requests.$prId'
import { Route as PpmpDocumentsNewRouteImport } from './routes/ppmp-documents.new'
import { Route as PpmpDocumentsDocIdRouteImport } from './routes/ppmp-documents.$docId'
import { Route as LibNewRouteImport } from './routes/lib.new'
import { Route as LibLibIdRouteImport } from './routes/lib.$libId'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsRoute = PurchaseRequestsRouteImport.update({
  id: '/purchase-requests',
  path: '/purchase-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PpmpDocumentsRoute = PpmpDocumentsRouteImport.update({
  id: '/ppmp-documents',
  path: '/ppmp-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibRoute = LibRouteImport.update({
  id: '/lib',
  path: '/lib',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalInboxRoute = ApprovalInboxRouteImport.update({
  id: '/approval-inbox',
  path: '/approval-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesPpmpRoute = ReferencesPpmpRouteImport.update({
  id: '/references/ppmp',
  path: '/references/ppmp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesBudgetRoute = ReferencesBudgetRouteImport.update({
  id: '/references/budget',
  path: '/references/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesAppNonCseRoute = ReferencesAppNonCseRouteImport.update({
  id: '/references/app-non-cse',
  path: '/references/app-non-cse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesAppCseRoute = ReferencesAppCseRouteImport.update({
  id: '/references/app-cse',
  path: '/references/app-cse',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsNewRoute = PurchaseRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchaseRequestsRoute,
} as any)
const PurchaseRequestsPrIdRoute = PurchaseRequestsPrIdRouteImport.update({
  id: '/$prId',
  path: '/$prId',
  getParentRoute: () => PurchaseRequestsRoute,
} as any)
const PpmpDocumentsNewRoute = PpmpDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PpmpDocumentsRoute,
} as any)
const PpmpDocumentsDocIdRoute = PpmpDocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => PpmpDocumentsRoute,
} as any)
const LibNewRoute = LibNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LibRoute,
} as any)
const LibLibIdRoute = LibLibIdRouteImport.update({
  id: '/$libId',
  path: '/$libId',
  getParentRoute: () => LibRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/lib': typeof LibRouteWithChildren
  '/login': typeof LoginRoute
  '/ppmp-documents': typeof PpmpDocumentsRouteWithChildren
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/lib/$libId': typeof LibLibIdRoute
  '/lib/new': typeof LibNewRoute
  '/ppmp-documents/$docId': typeof PpmpDocumentsDocIdRoute
  '/ppmp-documents/new': typeof PpmpDocumentsNewRoute
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/lib': typeof LibRouteWithChildren
  '/login': typeof LoginRoute
  '/ppmp-documents': typeof PpmpDocumentsRouteWithChildren
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/lib/$libId': typeof LibLibIdRoute
  '/lib/new': typeof LibNewRoute
  '/ppmp-documents/$docId': typeof PpmpDocumentsDocIdRoute
  '/ppmp-documents/new': typeof PpmpDocumentsNewRoute
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-inbox': typeof ApprovalInboxRoute
  '/audit-logs': typeof AuditLogsRoute
  '/lib': typeof LibRouteWithChildren
  '/login': typeof LoginRoute
  '/ppmp-documents': typeof PpmpDocumentsRouteWithChildren
  '/purchase-requests': typeof PurchaseRequestsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
  '/lib/$libId': typeof LibLibIdRoute
  '/lib/new': typeof LibNewRoute
  '/ppmp-documents/$docId': typeof PpmpDocumentsDocIdRoute
  '/ppmp-documents/new': typeof PpmpDocumentsNewRoute
  '/purchase-requests/$prId': typeof PurchaseRequestsPrIdRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/references/app-cse': typeof ReferencesAppCseRoute
  '/references/app-non-cse': typeof ReferencesAppNonCseRoute
  '/references/budget': typeof ReferencesBudgetRoute
  '/references/ppmp': typeof ReferencesPpmpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/lib'
    | '/login'
    | '/ppmp-documents'
    | '/purchase-requests'
    | '/reports'
    | '/settings'
    | '/users'
    | '/validation'
    | '/lib/$libId'
    | '/lib/new'
    | '/ppmp-documents/$docId'
    | '/ppmp-documents/new'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/lib'
    | '/login'
    | '/ppmp-documents'
    | '/purchase-requests'
    | '/reports'
    | '/settings'
    | '/users'
    | '/validation'
    | '/lib/$libId'
    | '/lib/new'
    | '/ppmp-documents/$docId'
    | '/ppmp-documents/new'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
  id:
    | '__root__'
    | '/'
    | '/approval-inbox'
    | '/audit-logs'
    | '/lib'
    | '/login'
    | '/ppmp-documents'
    | '/purchase-requests'
    | '/reports'
    | '/settings'
    | '/users'
    | '/validation'
    | '/lib/$libId'
    | '/lib/new'
    | '/ppmp-documents/$docId'
    | '/ppmp-documents/new'
    | '/purchase-requests/$prId'
    | '/purchase-requests/new'
    | '/references/app-cse'
    | '/references/app-non-cse'
    | '/references/budget'
    | '/references/ppmp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalInboxRoute: typeof ApprovalInboxRoute
  AuditLogsRoute: typeof AuditLogsRoute
  LibRoute: typeof LibRouteWithChildren
  LoginRoute: typeof LoginRoute
  PpmpDocumentsRoute: typeof PpmpDocumentsRouteWithChildren
  PurchaseRequestsRoute: typeof PurchaseRequestsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ValidationRoute: typeof ValidationRoute
  ReferencesAppCseRoute: typeof ReferencesAppCseRoute
  ReferencesAppNonCseRoute: typeof ReferencesAppNonCseRoute
  ReferencesBudgetRoute: typeof ReferencesBudgetRoute
  ReferencesPpmpRoute: typeof ReferencesPpmpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests': {
      id: '/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/purchase-requests'
      preLoaderRoute: typeof PurchaseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppmp-documents': {
      id: '/ppmp-documents'
      path: '/ppmp-documents'
      fullPath: '/ppmp-documents'
      preLoaderRoute: typeof PpmpDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lib': {
      id: '/lib'
      path: '/lib'
      fullPath: '/lib'
      preLoaderRoute: typeof LibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-inbox': {
      id: '/approval-inbox'
      path: '/approval-inbox'
      fullPath: '/approval-inbox'
      preLoaderRoute: typeof ApprovalInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/ppmp': {
      id: '/references/ppmp'
      path: '/references/ppmp'
      fullPath: '/references/ppmp'
      preLoaderRoute: typeof ReferencesPpmpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/budget': {
      id: '/references/budget'
      path: '/references/budget'
      fullPath: '/references/budget'
      preLoaderRoute: typeof ReferencesBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/app-non-cse': {
      id: '/references/app-non-cse'
      path: '/references/app-non-cse'
      fullPath: '/references/app-non-cse'
      preLoaderRoute: typeof ReferencesAppNonCseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references/app-cse': {
      id: '/references/app-cse'
      path: '/references/app-cse'
      fullPath: '/references/app-cse'
      preLoaderRoute: typeof ReferencesAppCseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/new': {
      id: '/purchase-requests/new'
      path: '/new'
      fullPath: '/purchase-requests/new'
      preLoaderRoute: typeof PurchaseRequestsNewRouteImport
      parentRoute: typeof PurchaseRequestsRoute
    }
    '/purchase-requests/$prId': {
      id: '/purchase-requests/$prId'
      path: '/$prId'
      fullPath: '/purchase-requests/$prId'
      preLoaderRoute: typeof PurchaseRequestsPrIdRouteImport
      parentRoute: typeof PurchaseRequestsRoute
    }
    '/ppmp-documents/new': {
      id: '/ppmp-documents/new'
      path: '/new'
      fullPath: '/ppmp-documents/new'
      preLoaderRoute: typeof PpmpDocumentsNewRouteImport
      parentRoute: typeof PpmpDocumentsRoute
    }
    '/ppmp-documents/$docId': {
      id: '/ppmp-documents/$docId'
      path: '/$docId'
      fullPath: '/ppmp-documents/$docId'
      preLoaderRoute: typeof PpmpDocumentsDocIdRouteImport
      parentRoute: typeof PpmpDocumentsRoute
    }
    '/lib/new': {
      id: '/lib/new'
      path: '/new'
      fullPath: '/lib/new'
      preLoaderRoute: typeof LibNewRouteImport
      parentRoute: typeof LibRoute
    }
    '/lib/$libId': {
      id: '/lib/$libId'
      path: '/$libId'
      fullPath: '/lib/$libId'
      preLoaderRoute: typeof LibLibIdRouteImport
      parentRoute: typeof LibRoute
    }
  }
}

interface LibRouteChildren {
  LibLibIdRoute: typeof LibLibIdRoute
  LibNewRoute: typeof LibNewRoute
}

const LibRouteChildren: LibRouteChildren = {
  LibLibIdRoute: LibLibIdRoute,
  LibNewRoute: LibNewRoute,
}

const LibRouteWithChildren = LibRoute._addFileChildren(LibRouteChildren)

interface PpmpDocumentsRouteChildren {
  PpmpDocumentsDocIdRoute: typeof PpmpDocumentsDocIdRoute
  PpmpDocumentsNewRoute: typeof PpmpDocumentsNewRoute
}

const PpmpDocumentsRouteChildren: PpmpDocumentsRouteChildren = {
  PpmpDocumentsDocIdRoute: PpmpDocumentsDocIdRoute,
  PpmpDocumentsNewRoute: PpmpDocumentsNewRoute,
}

const PpmpDocumentsRouteWithChildren = PpmpDocumentsRoute._addFileChildren(
  PpmpDocumentsRouteChildren,
)

interface PurchaseRequestsRouteChildren {
  PurchaseRequestsPrIdRoute: typeof PurchaseRequestsPrIdRoute
  PurchaseRequestsNewRoute: typeof PurchaseRequestsNewRoute
}

const PurchaseRequestsRouteChildren: PurchaseRequestsRouteChildren = {
  PurchaseRequestsPrIdRoute: PurchaseRequestsPrIdRoute,
  PurchaseRequestsNewRoute: PurchaseRequestsNewRoute,
}

const PurchaseRequestsRouteWithChildren =
  PurchaseRequestsRoute._addFileChildren(PurchaseRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalInboxRoute: ApprovalInboxRoute,
  AuditLogsRoute: AuditLogsRoute,
  LibRoute: LibRouteWithChildren,
  LoginRoute: LoginRoute,
  PpmpDocumentsRoute: PpmpDocumentsRouteWithChildren,
  PurchaseRequestsRoute: PurchaseRequestsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ValidationRoute: ValidationRoute,
  ReferencesAppCseRoute: ReferencesAppCseRoute,
  ReferencesAppNonCseRoute: ReferencesAppNonCseRoute,
  ReferencesBudgetRoute: ReferencesBudgetRoute,
  ReferencesPpmpRoute: ReferencesPpmpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
